version: '3.7'

services:

  nginx:
    container_name: hatorade-nginx
    # restart: unless-stopped
    build: ${PWD}/nginx-hatorade/
    volumes:
      - ${PWD}/nginx-hatorade/data/certbot/conf:/etc/letsencrypt
      - ${PWD}/nginx-hatorade/data/certbot/www:/var/www/certbot
      # - ${PWD}/nginx-hatorade/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/nginx-hatorade/no_frontend_or_logs.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    # command: service nginx start -c /etc/nginx/nginx.conf
    command: /bin/bash -c "sleep 8 && exec nginx -g 'daemon off;'"
    networks:
      nginx_network:
networks:
  nginx_network:
