version: '3.7'

services:

  nginx:
    container_name: hatorade-nginx
    restart: unless-stopped
    build: ./
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    networks:
      nginx_network:

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
networks:
  nginx_network:
